# Generated by Django 4.1.5 on 2023-01-17 11:09

import backendAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0002_files_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(max_length=10000, upload_to=backendAPI.models.getpath),
        ),
    ]
