# Generated by Django 4.1.5 on 2023-01-17 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0003_alter_files_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folderid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_Id', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='fid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendAPI.folderid'),
        ),
    ]
