# Generated by Django 4.1.5 on 2023-01-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0004_folderid_files_fid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='fid',
        ),
        migrations.DeleteModel(
            name='Folderid',
        ),
    ]
